Repository KIA-PROGRAMMING-38/Team_ItaCH_SmashLegends, pull requests merged in 2023-06, with the labels that each got.

#85 #13061
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_FirstAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerMove.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State.meta
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFinishAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFinishAttackState.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFirstAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFirstAttackState.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerRunState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerRunState.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSecondAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSecondAttackState.cs.meta
Labels: enhancement

#87 #13054
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_JumpUp.anim
  ItaCH_Smash_Legends/Assets/PlayerJumpState.cs
  ItaCH_Smash_Legends/Assets/PlayerJumpState.cs.meta
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerJump.cs
Labels: enhancement

#89 #13088
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_JumpDown.anim
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerJump.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerJumpState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerJumpState.cs.meta
Labels: enhancement

#91 #15079
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_Hang.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_HangFall.anim
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/PlayerHangController.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerJump.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHangState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHangState.cs.meta
Labels: enhancement

#94 [Fix] Fix Animator and Script
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller.meta
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerJump.cs
Labels: bug, enhancement

#97 #11050
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/M_Peter_Skin_000_Weapon.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Body.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Body.mat.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Face.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Face.mat.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Hair.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Hair.mat.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Weapon.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Weapon.mat.meta
  ItaCH_Smash_Legends/Assets/Scenes/UI.unity
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/.gitignore
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/CHANGELOG.md
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/CHANGELOG.md.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/CONTRIBUTING.md
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/CONTRIBUTING.md.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Editor.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Editor/CopyMaterialParameter.cs
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Editor/CopyMaterialParameter.cs.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Editor/Unity.UniversalToonShader.Urp.Editor.asmdef
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Editor/Unity.UniversalToonShader.Urp.Editor.asmdef.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Editor/UniversalToonGUI.cs
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Editor/UniversalToonGUI.cs.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/LICENSE.md
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/LICENSE.md.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/QAReport.md
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/QAReport.md.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/README.md
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/README.md.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/README_ja.md
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/README_ja.md.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToon.shader
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToon.shader.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonBody.hlsl
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonBody.hlsl.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonBodyDoubleShadeWithFeather.hlsl
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonBodyDoubleShadeWithFeather.hlsl.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonBodyShadingGradeMap.hlsl
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonBodyShadingGradeMap.hlsl.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonHead.hlsl
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonHead.hlsl.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonInput.hlsl
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonInput.hlsl.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonOutline.hlsl
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/Runtime/Shaders/UniversalToonOutline.hlsl.meta
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/package.json
  ItaCH_Smash_Legends/Assets/UnityChanToonShaderVer2_Project-urp-2.5.1/package.json.meta
Labels: enhancement

#105 #15080
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_HeavyAttack.anim
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerMove.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHeavyAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHeavyAttackState.cs.meta
Labels: enhancement

#114 #15106
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/AnimationHash.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHangController.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerJump.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerMove.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHangState.cs
Labels: enhancement

#113 #11098
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_FinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_FirstAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_Idle.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_SecondAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack00.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack01_0.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack01_0.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack01_1.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack01_1.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack02.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack_Smoke.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_HangSlash.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_LyingSlash.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Air_Burst.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Air_Jump.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Air_Slash.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Air_Smoke.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Ground.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Ground_Smoke.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Ult.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Ult_Start.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Ult_StartEffect.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Ult_end.prefab
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Effect.meta
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/EffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/EffectController.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/PeterEffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/PeterEffectController.cs.meta
  ItaCH_Smash_Legends/Assets/Settings/SampleSceneProfile.asset
Labels: enhancement

#121 #12025
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Map/SingleLogBridge/Prefab/Map.prefab
  ItaCH_Smash_Legends/Assets/Scenes/InGame.unity
  ItaCH_Smash_Legends/Assets/Script/GameManager.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/TeamType.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/TeamType.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Stage/GameMode.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
Labels: enhancement

#127 #12122
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Map/SingleLogBridge/Prefab/Map.prefab
  ItaCH_Smash_Legends/Assets/Resources/Map/SingleLogBridge/Prefab/Map.prefab.meta
  ItaCH_Smash_Legends/Assets/Script/Stage/DeadZone.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/DeadZone.cs.meta
  ItaCH_Smash_Legends/ProjectSettings/TagManager.asset
Labels: enhancement

#125 #15119
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerRollUp.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerRollUp.cs.meta
  ItaCH_Smash_Legends/Assets/Script/PlayerStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerIdleState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerJumpState.cs
Labels: enhancement

#126 #13111
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack00.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHangController.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs.meta
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerJump.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFinishAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFirstAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitState.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSecondAttackState.cs
Labels: enhancement

#120 #11101
  ItaCH_Smash_Legends/Assets/Scenes/UI.unity
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterDefaultStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/GameMode.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/Assets/UI/Prefab/LegendUI.prefab
  ItaCH_Smash_Legends/Assets/UI/Prefab/Main Camera.prefab
  ItaCH_Smash_Legends/Assets/UI/Prefab/Main Camera.prefab.meta
  ItaCH_Smash_Legends/Assets/UI/Prefab/ModeUI.prefab
  ItaCH_Smash_Legends/Assets/UI/Prefab/UI Camera.prefab
  ItaCH_Smash_Legends/Assets/UI/Prefab/UI Camera.prefab.meta
  ItaCH_Smash_Legends/Assets/UI/Script.meta
  ItaCH_Smash_Legends/Assets/UI/Script/LegendUI.cs
  ItaCH_Smash_Legends/Assets/UI/Script/LegendUI.cs.meta
  ItaCH_Smash_Legends/Assets/UI/Script/ModeUI.cs
  ItaCH_Smash_Legends/Assets/UI/Script/ModeUI.cs.meta
  ItaCH_Smash_Legends/ProjectSettings/TagManager.asset
Labels: enhancement

#132 #10131
  ItaCH_Smash_Legends/Assets/Scenes/UI.unity
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
Labels: bug

#135 #15128
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
Labels: enhancement

#136 #15129
  ItaCH_Smash_Legends/Assets/PlayerInput.inputactions
Labels: enhancement

#141 #12123
  ItaCH_Smash_Legends/Assets/Resources/Map/SingleLogBridge/Prefab/Map.prefab
  ItaCH_Smash_Legends/Assets/Script/PlayerHangController.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterDefaultStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/GameMode.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/Assets/UI/Script/LegendUI.cs
Labels: enhancement

#142 #15137
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_HeavyAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_JumpAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack02.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_HangSlash.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Ground.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/EffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/PeterEffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerJumpAttackState.cs
Labels: enhancement

#144 #12073
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/ProjectSettings/ProjectSettings.asset
Labels: enhancement

#146 #11102
  ItaCH_Smash_Legends/Assets/Resources/UI.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/HPBar_Blue_Frame.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/HPBar_Blue_Frame.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/HPBar_Red_Frame.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/HPBar_Red_Frame.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/JumpUI.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/JumpUI.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/LegendUI.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/LegendUI.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/ModeUI.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/ModeUI/ModeUI_01.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/ModeUI/ModeUI_01.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/PositionHelperUI.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/PositionHelperUI.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/UI Camera.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/UI Camera.prefab.meta
  ItaCH_Smash_Legends/Assets/Scenes/UI.unity
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/Assets/UI/Script/ModeUI.cs
  ItaCH_Smash_Legends/Assets/UI/Script/ScoreSet.cs
  ItaCH_Smash_Legends/Assets/UI/Script/ScoreSet.cs.meta
Labels: enhancement

#145 #13134
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/PlayerHitUpState.cs
  ItaCH_Smash_Legends/Assets/PlayerHitUpState.cs.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHeavyAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSecondAttackState.cs
Labels: enhancement

#149 #11148
  ItaCH_Smash_Legends/Assets/Resources/UI/LegendUI.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/ModeUI/ModeUI_01.prefab
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/UI/Script/ModeUI.cs
  ItaCH_Smash_Legends/Assets/UI/Script/Timer.cs
  ItaCH_Smash_Legends/Assets/UI/Script/Timer.cs.meta
Labels: enhancement

#150 [Feat] Implement End Game with time-over
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/GameMode.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
Labels: enhancement

#177 #11153
  ItaCH_Smash_Legends/Assets/Resources/UI/LobbyUI.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/LobbyUI.prefab.meta
  ItaCH_Smash_Legends/Assets/Scenes/UI.unity
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/Assets/UI/Animation.meta
  ItaCH_Smash_Legends/Assets/UI/Animation/ButtonAnimation.controller
  ItaCH_Smash_Legends/Assets/UI/Animation/ButtonAnimation.controller.meta
  ItaCH_Smash_Legends/Assets/UI/Script/Button.cs
  ItaCH_Smash_Legends/Assets/UI/Script/Button.cs.meta
  ItaCH_Smash_Legends/Assets/UI/Script/ModeUI.cs
  ItaCH_Smash_Legends/Assets/UI/Texture2D/GameStart.PNG
  ItaCH_Smash_Legends/Assets/UI/Texture2D/GameStart.PNG.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/LegendMenu.PNG
  ItaCH_Smash_Legends/Assets/UI/Texture2D/LegendMenu.PNG.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/LobbyUIAtlas.spriteatlas
  ItaCH_Smash_Legends/Assets/UI/Texture2D/LobbyUIAtlas.spriteatlas.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Common_Button_Purple.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Common_Button_Purple.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Icon_Setting.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Icon_Setting.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Mode_Harvest_ProfileAddonGradient.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Mode_Harvest_ProfileAddonGradient.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_ProfileFrame_001_Normal.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_ProfileFrame_001_Normal.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Profile_Common_001_Normal.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Profile_Common_001_Normal.png.meta
Labels: enhancement

#178 #12169
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/DeadZone.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/Assets/UI/Script/LegendUI.cs
Labels: enhancement

#180 #12176
  README.md
Labels: documentation

#179 #15172
  ItaCH_Smash_Legends/Assets/PlayerInput.inputactions
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
Labels: enhancement

#186 [Feature] Start 2nd Milestone
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/PlayerInput.inputactions
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/LobbyUI.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/LobbyUI.prefab.meta
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Scenes/UI.unity
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerJump.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitUpState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerJumpState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/DeadZone.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/Assets/UI/Animation.meta
  ItaCH_Smash_Legends/Assets/UI/Animation/ButtonAnimation.controller
  ItaCH_Smash_Legends/Assets/UI/Animation/ButtonAnimation.controller.meta
  ItaCH_Smash_Legends/Assets/UI/Script/Button.cs
  ItaCH_Smash_Legends/Assets/UI/Script/Button.cs.meta
  ItaCH_Smash_Legends/Assets/UI/Script/LegendUI.cs
  ItaCH_Smash_Legends/Assets/UI/Script/ModeUI.cs
  ItaCH_Smash_Legends/Assets/UI/Texture2D/GameStart.PNG
  ItaCH_Smash_Legends/Assets/UI/Texture2D/GameStart.PNG.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/LegendMenu.PNG
  ItaCH_Smash_Legends/Assets/UI/Texture2D/LegendMenu.PNG.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/LobbyUIAtlas.spriteatlas
  ItaCH_Smash_Legends/Assets/UI/Texture2D/LobbyUIAtlas.spriteatlas.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Common_Button_Purple.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Common_Button_Purple.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Icon_Setting.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Icon_Setting.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Mode_Harvest_ProfileAddonGradient.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Mode_Harvest_ProfileAddonGradient.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_ProfileFrame_001_Normal.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_ProfileFrame_001_Normal.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Profile_Common_001_Normal.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Profile_Common_001_Normal.png.meta
  ItaCH_Smash_Legends/ProjectSettings/DynamicsManager.asset
  ItaCH_Smash_Legends/ProjectSettings/Physics2DSettings.asset
  README.md
Labels: enhancement

#188 #15187
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
Labels: bug

#193 #15184
  ItaCH_Smash_Legends/Assets/Animator/Hook.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook.controller
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook.controller.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_DownIdle.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_DownIdle.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_FinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_FinishAttack.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_FirstAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_FirstAttack.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_Hang.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_Hang.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HangFall.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HangFall.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HangJumpUp.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HangJumpUp.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HeavyAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HeavyAttack.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_Hit.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_Hit.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HitDown.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HitDown.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HitLanding.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HitLanding.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HitUp.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HitUp.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HoldIdle.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HoldIdle.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_Idle.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_Idle.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpDown.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpDown.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpFinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpFinishAttack.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpFirstAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpFirstAttack.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpLanding.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpLanding.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpSecondAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpSecondAttack.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpUp.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpUp.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_RollUpBack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_RollUpBack.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_RollUpFront.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_RollUpFront.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_Run.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_Run.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_SkillAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_SkillAttack.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_StandUp.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_StandUp.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_StartIdle.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_StartIdle.anim.meta
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Ingame.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/PF_Hook_Skin000_Ingame.fbx.meta
  ItaCH_Smash_Legends/Assets/Scenes/Character.unity
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHangController.cs
Labels: enhancement

#195 #15152
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook.controller
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_FinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_FirstAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Hook/Hook_Attack_Bullet.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Hook/Hook_Attack_Bullet_Disappear.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity.meta
  ItaCH_Smash_Legends/Assets/Script/Hook.meta
  ItaCH_Smash_Legends/Assets/Script/Hook/HookAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookAttack.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Hook/HookBullet.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookBullet.cs.meta
  ItaCH_Smash_Legends/Assets/Script/IAttack.cs
  ItaCH_Smash_Legends/Assets/Script/IAttack.cs.meta
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFinishAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFirstAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHeavyAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerJumpAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSecondAttackState.cs
Labels: enhancement

#199 #15163
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity
  ItaCH_Smash_Legends/Assets/Script/Hook/HookAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
Labels: enhancement

#201 #13197
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_SecondAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Ground.prefab
  ItaCH_Smash_Legends/Assets/Script/IHit.cs
  ItaCH_Smash_Legends/Assets/Script/IHit.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Peter.meta
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterHit.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterHit.cs.meta
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitDownState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitDownState.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitUpState.cs
Labels: enhancement

#208 #13207
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_FinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_FirstAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/PF_Alice_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack00.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack00_Decal.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack01.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceEffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceEffectController.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterEffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterEffectController.cs.meta
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/EffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/PeterEffectController.cs
Labels: enhancement

#215 #12213
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/GameMode.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
Labels: enhancement

#220 #15219
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook.controller
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_FinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_FirstAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_HeavyAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_SecondAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity
  ItaCH_Smash_Legends/Assets/Script/Hook/HookAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitUpState.cs
Labels: enhancement

#223 #13209
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice.overrideController
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_HeavyAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/PF_Alice_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack00.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack01.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack_Air.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Smash_End.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Smash_End_Explosion.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Smash_Mine.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Smash_Start.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceBomb.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceBomb.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceEffectController.cs
  ItaCH_Smash_Legends/ProjectSettings/TagManager.asset
Labels: enhancement

#224 #13210
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice.overrideController
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_SkillAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Ult.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Ult_StartEffect.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceEffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSkillAttackState.cs
Labels: enhancement

#226 #11192
  ItaCH_Smash_Legends/Assets/Resources/UI/Frame.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/Frame.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/LegendPanel.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/LegendPanel.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/LobbyUI.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/MatchingPanel.prefab
  ItaCH_Smash_Legends/Assets/Scenes/UI.unity
  ItaCH_Smash_Legends/Assets/UI/Script/ButtonScaler.cs
  ItaCH_Smash_Legends/Assets/UI/Script/ButtonScaler.cs.meta
  ItaCH_Smash_Legends/Assets/UI/Script/LegendMenuUI.cs
  ItaCH_Smash_Legends/Assets/UI/Script/LegendMenuUI.cs.meta
  ItaCH_Smash_Legends/Assets/UI/Script/LegendSelectUI.cs
  ItaCH_Smash_Legends/Assets/UI/Script/LegendSelectUI.cs.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/Sprite-0001.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/Sprite-0001.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Base_Check.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Base_Check.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Portrait_Large_Alice.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Portrait_Large_Alice.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Portrait_Large_Hook.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Portrait_Large_Hook.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Portrait_Large_Peter.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Portrait_Large_Peter.png.meta
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Setting_CustomKey_RectKeySelected.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Setting_CustomKey_RectKeySelected.png.meta
Labels: enhancement

#234 #13211
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice.overrideController
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Smash_End_Explosion.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceBomb.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceExplosion.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceExplosion.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceHit.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceHit.cs.meta
Labels: enhancement

#235 #15230
  ItaCH_Smash_Legends/Assets/Script/Hook/HookAttack.cs
Labels: enhancement

#242 #12236
  ItaCH_Smash_Legends/Assets/Resources/UI/LobbyUI.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Matching.unity
  ItaCH_Smash_Legends/Assets/Scenes/Matching.unity.meta
  ItaCH_Smash_Legends/Assets/Script/GameManager.cs
  ItaCH_Smash_Legends/Assets/Script/Lobby.meta
  ItaCH_Smash_Legends/Assets/Script/Lobby/LobbyManager.cs
  ItaCH_Smash_Legends/Assets/Script/Lobby/LobbyManager.cs.meta
  ItaCH_Smash_Legends/Assets/Script/UserData.cs
  ItaCH_Smash_Legends/Assets/Script/UserData.cs.meta
  ItaCH_Smash_Legends/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#243 #13225
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice.overrideController
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_FinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_SkillAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_Hang.anim
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Ult.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceBomb.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceEffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceExplosion.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceHit.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSkillAttackState.cs
  ItaCH_Smash_Legends/ProjectSettings/DynamicsManager.asset
Labels: enhancement

#246 #13239
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceHit.cs
  ItaCH_Smash_Legends/Assets/Script/IHit.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFinishAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFirstAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerJumpAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerJumpDownState.cs
Labels: enhancement

#247 #13173
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_HangSlash.prefab
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterHit.cs
Labels: enhancement

#250 #13231
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSkillAttackState.cs
Labels: enhancement

#251 #13151
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice.overrideController
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_SkillAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_FinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_FirstAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_HeavyAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_JumpUp.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_SecondAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_SkillAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Ult.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack01_0.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack01_1.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack_Smoke.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Ground.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Ult.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Ult_end.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterEffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerIdleState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerStartIdleState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerStartIdleState.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
Labels: enhancement

#256 #11140
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Body.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Body.mat.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Face.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Face.mat.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Hair.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Hair.mat.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Weapon.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Weapon.mat.meta
Labels: enhancement

#253 #15229
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook.controller
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_HeavyAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_JumpFinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceHit.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookBullet.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHeavyHit.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHeavyHit.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHit.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHit.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Hook/HookSkillHit.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookSkillHit.cs.meta
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFirstAttackState.cs
Labels: enhancement

#257 #11103
  ItaCH_Smash_Legends/Assets/Resources/UI/Frame.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/ModeUI/ModeUI_01.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter.png.meta
  ItaCH_Smash_Legends/Assets/Scenes/InGame.unity
  ItaCH_Smash_Legends/Assets/Scenes/UI.unity
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/Assets/Script/UI/HealthBar.cs
  ItaCH_Smash_Legends/Assets/Script/UI/LogInUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/ModeUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/Portrait.cs
  ItaCH_Smash_Legends/Assets/Script/UI/Portrait.cs.meta
  ItaCH_Smash_Legends/Assets/Script/UI/RespawnTimer.cs
  ItaCH_Smash_Legends/Assets/Script/UI/RespawnTimer.cs.meta
  ItaCH_Smash_Legends/Assets/Script/UI/RotatingImage.cs
  ItaCH_Smash_Legends/Assets/Script/UI/RotatingImage.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Util/Method.cs
  ItaCH_Smash_Legends/Assets/Script/Util/Path.cs
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Setting_CustomKey_RectKeySelected.png
  ItaCH_Smash_Legends/Assets/UI/Texture2D/T_UI_Setting_CustomKey_RectKeySelected.png.meta
Labels: enhancement

#259 #15258
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice.overrideController
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook.controller
  ItaCH_Smash_Legends/Assets/Animator/Hook/Hook_RollUpBack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter.controller
  ItaCH_Smash_Legends/Assets/PlayerInput.inputactions
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/Alice_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/Alice_Ingame.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/PF_Alice_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/PF_Alice_Ingame.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Scenes/InGame.unity
  ItaCH_Smash_Legends/Assets/Script/Hook/HookAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookBullet.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHit.cs
  ItaCH_Smash_Legends/Assets/Script/Lobby/LobbyManager.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerInput.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerRollUp.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerDownIdleState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerDownIdleState.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitDownState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerIdleState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerJumpState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/Assets/Skybox.meta
  ItaCH_Smash_Legends/Assets/Skybox/Cubemaps.meta
  ItaCH_Smash_Legends/Assets/Skybox/Cubemaps/daytime.hdr.meta
  ItaCH_Smash_Legends/Assets/Skybox/Cubemaps/sunset.hdr.meta
  ItaCH_Smash_Legends/Assets/Skybox/Materials.meta
  ItaCH_Smash_Legends/Assets/Skybox/Materials/Skybox_Daytime.mat
  ItaCH_Smash_Legends/Assets/Skybox/Materials/Skybox_Daytime.mat.meta
  ItaCH_Smash_Legends/Assets/Skybox/Materials/Skybox_Sunset.mat
  ItaCH_Smash_Legends/Assets/Skybox/Materials/Skybox_Sunset.mat.meta
  ItaCH_Smash_Legends/Assets/Skybox/Scene.meta
  ItaCH_Smash_Legends/Assets/Skybox/Scene/mainScene.unity
  ItaCH_Smash_Legends/Assets/Skybox/Scene/mainScene.unity.meta
  ItaCH_Smash_Legends/Assets/Skybox/Scene/mainSceneSettings.lighting
  ItaCH_Smash_Legends/Assets/Skybox/Scene/mainSceneSettings.lighting.meta
Labels: bug, enhancement

#276 #13262
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_SkillAttack.anim
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceHit.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerIdleState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerRunState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSkillAttackState.cs
Labels: enhancement

#277 #15266
  ItaCH_Smash_Legends/Assets/Resources/Charater/CharacterData.meta
  ItaCH_Smash_Legends/Assets/Resources/Charater/CharacterData/CharacterDefaultStatusData.csv
  ItaCH_Smash_Legends/Assets/Resources/Charater/CharacterData/CharacterDefaultStatusData.csv.meta
  ItaCH_Smash_Legends/Assets/Script/Util/Path.cs
Labels: documentation, enhancement

#278 #12274
  ItaCH_Smash_Legends/Assets/Scenes/InGame.meta
  ItaCH_Smash_Legends/Assets/Scenes/InGame.unity
  ItaCH_Smash_Legends/Assets/Scenes/InGame/LightingData.asset
  ItaCH_Smash_Legends/Assets/Scenes/InGame/LightingData.asset.meta
  ItaCH_Smash_Legends/Assets/Scenes/InGame/ReflectionProbe-0.exr
  ItaCH_Smash_Legends/Assets/Scenes/InGame/ReflectionProbe-0.exr.meta
  ItaCH_Smash_Legends/Assets/Scenes/LightSettingForDevelopment.lighting
  ItaCH_Smash_Legends/Assets/Scenes/LightSettingForDevelopment.lighting.meta
  ItaCH_Smash_Legends/Assets/Scenes/Lobby.meta
  ItaCH_Smash_Legends/Assets/Scenes/Lobby.unity
  ItaCH_Smash_Legends/Assets/Scenes/Lobby/LightingData.asset
  ItaCH_Smash_Legends/Assets/Scenes/Lobby/LightingData.asset.meta
  ItaCH_Smash_Legends/Assets/Scenes/Lobby/ReflectionProbe-0.exr
  ItaCH_Smash_Legends/Assets/Scenes/Lobby/ReflectionProbe-0.exr.meta
  ItaCH_Smash_Legends/Assets/Script/GameManager.cs
  ItaCH_Smash_Legends/Assets/Script/Lobby/LobbyManager.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
Labels: enhancement

#283 #13275
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_FinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_FirstAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_JumpAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Alice/Alice_SkillAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_FinishAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_FirstAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_HeavyAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_JumpAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_SecondAttack.anim
  ItaCH_Smash_Legends/Assets/Animator/Peter/Peter_SkillAttack.anim
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/Alice_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack00.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack00_Decal.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack01.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Attack_Air.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Smash_End_Explosion.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Smash_Start.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Alice/Alice_Ult.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack00.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack01_1.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Attack02.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_HangSlash.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Smash_Ground.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Peter/Peter_Ult_end.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceHit.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterHit.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerFirstAttackState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerSkillAttackState.cs
Labels: enhancement

#284 #15268
  ItaCH_Smash_Legends/Assets/Resources/Charater/CharacterData/CharacterDefaultStatusData.csv
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceHit.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHeavyHit.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHit.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookSkillHit.cs
  ItaCH_Smash_Legends/Assets/Script/Peter/PeterHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerJump.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerMove.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterDefaultData.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterDefaultData.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterDefaultStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/DataTable.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/DataTable.cs.meta
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
Labels: enhancement

#290 #15271
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/Alice_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Common/Common_Smash_Smoke.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Hook/Hook_Jump_Smoke.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHit.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/EffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/DeadZone.cs
Labels: enhancement

#291 #12279
  ItaCH_Smash_Legends/Assets/Photon/PhotonRealtime/Code/Player.cs
  ItaCH_Smash_Legends/Assets/Resources/UI/ModeUI/ModeUI_01.prefab
  ItaCH_Smash_Legends/Assets/Script/Lobby/LobbyManager.cs
  ItaCH_Smash_Legends/Assets/Script/UI/LegendMenuUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/LegendSelectUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/LobbyUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/LogInUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/MatchUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/ModeUI.cs
  ItaCH_Smash_Legends/Assets/Script/User/UserData.cs
  ItaCH_Smash_Legends/Assets/Script/User/UserManager.cs
  ItaCH_Smash_Legends/Assets/Script/Util/Enum.cs
  ItaCH_Smash_Legends/Assets/Script/Util/Path.cs
  ItaCH_Smash_Legends/ProjectSettings/EditorBuildSettings.asset
Labels: enhancement

#296 #15272
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/Alice_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Body.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Face.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Hair.mat
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Peter/Peter_Ingame/Peter_Weapon.mat
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/EffectController.cs
Labels: enhancement

#308 #13305
  ItaCH_Smash_Legends/Assets/Resources/Charater/Alice/Alice_Ingame/Alice_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Alice.unity
  ItaCH_Smash_Legends/Assets/Script/Alice/AliceBomb.cs
  ItaCH_Smash_Legends/Assets/Script/Util/CharacterTestModule.cs
Labels: enhancement

#307 #15302
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Default_Bullet_Delete_Effect.prefab
  ItaCH_Smash_Legends/Assets/Resources/Charater/Hook/Hook_Ingame/Hook_Ingame.prefab
  ItaCH_Smash_Legends/Assets/Resources/Effect/Hook/Hook_Jump_Smoke.prefab
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity
  ItaCH_Smash_Legends/Assets/Script/Hook/HookBullet.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookEffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHangController.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerRollUp.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Effect/EffectController.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHangState.cs
  ItaCH_Smash_Legends/Assets/Script/Player_State/PlayerHitState.cs
Labels: enhancement, Important

#325 #15313
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/DeadZone.cs
Labels: bug, enhancement

#311 #11233
  ItaCH_Smash_Legends/Assets/Resources/Sound/AudioMixer.mixer
  ItaCH_Smash_Legends/Assets/Sound/SoundManager.cs
  ItaCH_Smash_Legends/Assets/Sound/SoundSource.cs
Labels: enhancement

#324 #11288
  ItaCH_Smash_Legends/Assets/Script/UI/Portrait.cs
  ItaCH_Smash_Legends/Assets/Script/UI/RotatingImage.cs
Labels: bug

#335 #15314
  ItaCH_Smash_Legends/Assets/Scenes/Hook.unity
  ItaCH_Smash_Legends/Assets/Script/Hook/HookAttack.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookBullet.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHeavyHit.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookHit.cs
  ItaCH_Smash_Legends/Assets/Script/Hook/HookSkillHit.cs
  ItaCH_Smash_Legends/Assets/Script/PlayerAttack.cs
Labels: bug, enhancement, Important

#333 #13304
  ItaCH_Smash_Legends/Assets/Resources/UI/MobileUI.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/MobileUI/MobileUI.prefab
  ItaCH_Smash_Legends/Assets/Resources/UI/MobileUI/MobileUI.prefab.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice/Alice.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice/Alice.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice/Alice_DefaultAttackIcon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice/Alice_DefaultAttackIcon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice/Alice_HeavyAttackIcon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice/Alice_HeavyAttackIcon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice/Alice_SkillAttackIcon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Alice/Alice_SkillAttackIcon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Character_Jump_Icon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Character_Jump_Icon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook/Hook.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook/Hook.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook/Hook_DefaultAttackIcon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook/Hook_DefaultAttackIcon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook/Hook_HeavyAttackIcon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook/Hook_HeavyAttackIcon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook/Hook_SkillAttackIcon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Hook/Hook_SkillAttackIcon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter/Peter.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter/Peter.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter/Peter_DefaultAttackIcon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter/Peter_DefaultAttackIcon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter/Peter_HeavyAttackIcon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter/Peter_HeavyAttackIcon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter/Peter_SkillAttackIcon.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/Peter/Peter_SkillAttackIcon.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Attack_Outline.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Attack_Outline.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Move_Outline.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Move_Outline.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Move_Outline2.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Move_Outline2.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Move_Point.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Move_Point.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Move_Point_Outline.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Move_Point_Outline.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Secondary_Outline.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Secondary_Outline.png.meta
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Shadow.png
  ItaCH_Smash_Legends/Assets/Resources/UI/Sprite/TouchController/Shadow.png.meta
  ItaCH_Smash_Legends/Assets/Scenes/Mobile UI.unity
  ItaCH_Smash_Legends/Assets/Scenes/Mobile UI.unity.meta
Labels: enhancement

#337 #15328
  ItaCH_Smash_Legends/Assets/Script/Hook/HookBullet.cs
  ItaCH_Smash_Legends/Assets/Script/Player_Status/DataTable.cs
  ItaCH_Smash_Legends/Assets/Script/ResourcesManager.cs
  ItaCH_Smash_Legends/Assets/Script/ResourcesManager.cs.meta
  ItaCH_Smash_Legends/Assets/Script/UI/LobbyUI.cs
  ItaCH_Smash_Legends/Assets/Script/Util/Path.cs
Labels: enhancement

#339 #12280
  ItaCH_Smash_Legends/Assets/Script/Player_Status/CharacterStatus.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/DeadZone.cs
  ItaCH_Smash_Legends/Assets/Script/Stage/StageManager.cs
  ItaCH_Smash_Legends/Assets/Script/UI/LegendMenuUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/LobbyUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/ModeUI.cs
  ItaCH_Smash_Legends/Assets/Script/UI/RespawnTimer.cs
  ItaCH_Smash_Legends/Assets/Script/User/UserData.cs
  ItaCH_Smash_Legends/Assets/Script/User/UserManager.cs
  ItaCH_Smash_Legends/Assets/Script/Util/CharacterType.cs
Labels: bug, enhancement
